version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ (AMQP protocol)
      - '15672:15672' # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auth-service
    command: node dist/apps/auth-service/main.js
    ports:
      - '3001:3001'
    env_file: .env
    volumes:
      - /app/node_modules

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: product-service
    command: node dist/apps/product-service/main.js
    ports:
      - '3002:3002'
    env_file: .env
    volumes:
      - /app/node_modules
